--OLAP Processing

--1.Count Sentiments by Company and Date
SELECT COMPANY_NAME, ANALYSIS_DATE, SENTIMENT, COUNT(*) AS COUNT
FROM SENTIMENT_DB.PUBLIC.SENTIMENT_ANALYSIS
GROUP BY COMPANY_NAME, ANALYSIS_DATE, SENTIMENT;

--2.Average Sentiment Score per Company
SELECT COMPANY_NAME, AVG(SENTIMENT_SCORE) AS AVG_SENTIMENT_SCORE
FROM (
    SELECT COMPANY_NAME, SENTIMENT, CASE WHEN SENTIMENT = 'Positive' THEN 1
                                        WHEN SENTIMENT = 'Neutral' THEN 0
                                        WHEN SENTIMENT = 'Negative' THEN -1
                                        ELSE NULL END AS SENTIMENT_SCORE
    FROM SENTIMENT_DB.PUBLIC.SENTIMENT_ANALYSIS
)
GROUP BY COMPANY_NAME;

--3.Top Competitors by Mention Count
SELECT COMPETITORS, COUNT(*) AS MENTION_COUNT
FROM SENTIMENT_DB.PUBLIC.SENTIMENT_ANALYSIS
WHERE COMPETITORS IS NOT NULL
GROUP BY COMPETITORS
ORDER BY MENTION_COUNT DESC
LIMIT 10;

--4.Sentiment Trend Over Time
SELECT ANALYSIS_DATE, SENTIMENT, COUNT(*) AS COUNT
FROM SENTIMENT_DB.PUBLIC.SENTIMENT_ANALYSIS
GROUP BY ANALYSIS_DATE, SENTIMENT
ORDER BY ANALYSIS_DATE;

--5.Daily Summary
SELECT ANALYSIS_DATE, SENTIMENT, COUNT(*) AS MENTION_COUNT
FROM SENTIMENT_DB.PUBLIC.SENTIMENT_ANALYSIS
GROUP BY ANALYSIS_DATE, SENTIMENT;

